"""Initial schema: users, companies, orders, reports, objects, npa, tax_rates, market_data

Revision ID: 9c2145e7123b
Revises: 
Create Date: 2026-03-12 22:10:26.069070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c2145e7123b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appraisal_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_inn', sa.String(length=12), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('valuation_purpose', sa.Text(), nullable=False),
    sa.Column('valuation_type', sa.Enum('MARKET', 'CADASTRAL', 'INVESTMENT', 'LIQUIDATION', 'FAIR_VALUE', name='valuationtype'), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('report_validity_months', sa.Integer(), nullable=False),
    sa.Column('usage_restrictions', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_date', 'appraisal_orders', ['order_date'], unique=False)
    op.create_index('ix_orders_valuation_date', 'appraisal_orders', ['valuation_date'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('object_type', sa.Enum('REAL_ESTATE', 'MOVABLE_PROPERTY', 'BUSINESS', 'INTANGIBLE', 'RECEIVABLES', 'SECURITIES', name='objecttype'), nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('land_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('building_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('offer_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('extra_params', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_object_type'), 'market_data', ['object_type'], unique=False)
    op.create_index(op.f('ix_market_data_region_code'), 'market_data', ['region_code'], unique=False)
    op.create_index('ix_market_date', 'market_data', ['transaction_date', 'offer_date'], unique=False)
    op.create_index('ix_market_type_region', 'market_data', ['data_type', 'object_type', 'region_code'], unique=False)
    op.create_table('npa_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('npa_level', sa.Enum('FEDERAL_LAW', 'GOVERNMENT_DECREE', 'MINISTRY_ORDER', 'LOCAL', name='npalevel'), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('document_date', sa.Date(), nullable=False),
    sa.Column('issuing_author', sa.String(length=255), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number', 'document_date', name='uq_npa_doc')
    )
    op.create_index('ix_npa_level_active', 'npa_registry', ['npa_level', 'is_active'], unique=False)
    op.create_index(op.f('ix_npa_registry_is_active'), 'npa_registry', ['is_active'], unique=False)
    op.create_table('regional_tax_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_code', sa.String(length=10), nullable=False),
    sa.Column('region_name', sa.String(length=255), nullable=False),
    sa.Column('tax_type', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('object_category', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('legal_basis', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_code', 'tax_type', 'year', 'object_category', name='uq_tax_rate')
    )
    op.create_index(op.f('ix_regional_tax_rates_region_code'), 'regional_tax_rates', ['region_code'], unique=False)
    op.create_index(op.f('ix_regional_tax_rates_year'), 'regional_tax_rates', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('sro_membership_id', sa.String(length=100), nullable=True),
    sa.Column('qual_certificate_number', sa.String(length=100), nullable=True),
    sa.Column('qual_certificate_expiry', sa.Date(), nullable=True),
    sa.Column('insurance_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('legal_address', sa.Text(), nullable=True),
    sa.Column('actual_address', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('sro_name', sa.String(length=255), nullable=True),
    sa.Column('sro_inn', sa.String(length=12), nullable=True),
    sa.Column('compensation_fund', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_inn'), 'companies', ['inn'], unique=True)
    op.create_table('appraisal_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('appraiser_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATION', 'VERIFICATION', 'FINAL', name='reportstatus'), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('final_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('final_value_type', sa.Enum('MARKET', 'CADASTRAL', 'INVESTMENT', 'LIQUIDATION', 'FAIR_VALUE', name='valuationtype'), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appraiser_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['appraisal_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_number')
    )
    op.create_index(op.f('ix_appraisal_reports_status'), 'appraisal_reports', ['status'], unique=False)
    op.create_index('ix_reports_status_date', 'appraisal_reports', ['status', 'report_date'], unique=False)
    op.create_table('appraisal_objects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.Enum('REAL_ESTATE', 'MOVABLE_PROPERTY', 'BUSINESS', 'INTANGIBLE', 'RECEIVABLES', 'SECURITIES', name='objecttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('cadastral_number', sa.String(length=50), nullable=True),
    sa.Column('conditional_number', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('land_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('building_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('ownership_type', sa.String(length=100), nullable=True),
    sa.Column('balance_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('residual_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('restrictions', sa.Text(), nullable=True),
    sa.Column('encumbrances', sa.Text(), nullable=True),
    sa.Column('is_state_owned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['appraisal_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appraisal_objects_cadastral_number'), 'appraisal_objects', ['cadastral_number'], unique=False)
    op.create_index(op.f('ix_appraisal_objects_object_type'), 'appraisal_objects', ['object_type'], unique=False)
    op.create_index('ix_objects_type_report', 'appraisal_objects', ['object_type', 'report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_objects_type_report', table_name='appraisal_objects')
    op.drop_index(op.f('ix_appraisal_objects_object_type'), table_name='appraisal_objects')
    op.drop_index(op.f('ix_appraisal_objects_cadastral_number'), table_name='appraisal_objects')
    op.drop_table('appraisal_objects')
    op.drop_index('ix_reports_status_date', table_name='appraisal_reports')
    op.drop_index(op.f('ix_appraisal_reports_status'), table_name='appraisal_reports')
    op.drop_table('appraisal_reports')
    op.drop_index(op.f('ix_companies_inn'), table_name='companies')
    op.drop_table('companies')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regional_tax_rates_year'), table_name='regional_tax_rates')
    op.drop_index(op.f('ix_regional_tax_rates_region_code'), table_name='regional_tax_rates')
    op.drop_table('regional_tax_rates')
    op.drop_index(op.f('ix_npa_registry_is_active'), table_name='npa_registry')
    op.drop_index('ix_npa_level_active', table_name='npa_registry')
    op.drop_table('npa_registry')
    op.drop_index('ix_market_type_region', table_name='market_data')
    op.drop_index('ix_market_date', table_name='market_data')
    op.drop_index(op.f('ix_market_data_region_code'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_object_type'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index('ix_orders_valuation_date', table_name='appraisal_orders')
    op.drop_index('ix_orders_date', table_name='appraisal_orders')
    op.drop_table('appraisal_orders')
    # ### end Alembic commands ###
